---
title: "Indicadores_fundamentalistas"
author: ""
date: ""
output: html_document
---



 variável|localização =  tabela e acc.number ou tabela e coluna
:-------:|:----------:
 lucro liquido = Lucro/Prejuízo Consolidado do Período | fr.income.consolidated 3.11
 nº de ações = quantidade de ações | current.stock.composition number.of.stocks
 Patrimônio Líquido Consolidado | fr.liabilities.consolidated 2.03
 receita liquída = Receita de Venda de Bens e/ou Serviços | fr.income.consolidated 3.01
 Dividend Yield | history.dividends dividend.by.price
 valor dos dividendos | history.dividends value
 ativo circulante | fr.assets.consolidated 1.01
 passivo circulante | fr.assets.consolidated 2.01
 
 



## Indicadores de Balanço

### Liquidez corrente (LC)

$$LC=\frac{Ativo\ circulante}{passivo\ circulante}$$

### Valor patrimonial da ação (VPA)
$$VPA=\frac{patrimônio\ líquido}{quantidade\ de\ ações}$$

### Lucro por Ação (LPA)



  $$LPA=\frac{Lucro\ Líquido}{Quantidade\ de\ ações}$$


## Indicadores de mercado

### Preço/lucro (P/L)


 $$P/L=\frac{Cotação\ da\ ação}{Lucro\ por\ ação}$$

### Taxa de retorno do investimento (TR)


 $$TR=\frac{1}{PL} * 100$$

### Relação preço/valor patrimonial (P/VP)


 $$P/PV=\frac{cotação\ da\ ação}{valor\ patrimonial\ da\ ação(VPA)}$$

### Price Sales Ratio (PSR)


 $$PSR=\frac{cotação\ da\ ação}{(receita\ líquida/quantidade\ de\ ações)}$$

### Pay-Out


 $$Pay-out=( \frac{valor\ dos\ dividendos}{LPA})*100$$

### Dividend Yield (DY)


 $$DY=(\frac{valor\ dos\ dividendos}{cotação\ da\ ação})*100$$




